[project]
name = "txt-to-xlsx"
version = "0.1.0"
description = "PyQt6 Gui app to convert from .txt to .xlsx"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logging>=0.4.9.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pyinstaller>=6.14.2",
    "pyqt6>=6.9.1",
]
